import Image from "next/image";
import styles from "../styles/Home.module.css";
import "../styles/globals.css";
import Canvas from "../components/Canvas";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "with-jotai",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <div>
      <Canvas />
    </div>
  );
}
